### ISSUE TITLE
runTLSSocket and runSettingsSocket functions have different behavior.

### ISSUE THREAD

**Issue by TravisWhitaker** [yesodweb/wai#361] opened 2015-04-07 19:13 UTC
I've been using constructs a bit like the following to implement graceful shutdown initiated by an MVar:

    safeShutdown :: MVar () -> MVar () -> Socket -> IO ()
    safeShutdown init_term warp_dead sock = do
        takeMVar init_term
        close socket
        takeMVar warp_dead
    
    -- Assumes warp is invoked with something like this:
    
    let ws = setPort 10000 defaultSettings
    s <- bindPortTCP (getPort ws) (getHost ws)
    wd <- newEmptyMVar
    forkFinally (runSettingsSocket ws s app) (const $ putMVar wd ())

Documentation for the 'runSettingsSocket' function states that "When the listen socket in the second argument is closed, all live connections are gracefully shut down." The idea is to close the listening socket, then wait for the warp thread to exit. And this works perfectly in the above case. However, if 'runTLSSocket' from 'warp-tls' is used:

    let ws = setPort 10000 defaultSettings
    let ts = defaultTlsSettings {certFile = "cert", keyFile = "key"}
    s <- bindPortTCP (getPort ws) (getHost ws)
    wd <- newEmptyMVar
    forkFinally (runTLSSocket ts ws s app) (const $ putMVar wd ())

In this case 'safeShutdown' seems to block indefinitely on the warp thread exiting. I noticed a few things comparing the 'runTLSSocket' and 'runSettingsSocket' functions. 'runSettingsSocket' calls the 'settingsInstallShutdownHandler' function, while runTLSSocket seems to ignore it. 'runTLSSocket' calls 'runSettingsConnectionMakerSecure' directly, while 'runSettingsSocket' involves a call to the 'runSettingsConnection' function, which in turn calls the 'runSettingsConnectionMaker', which finally calls the 'runSettingsConnectionMakerSecure' function. I suspect that this is the cause of the differences in behavior between the 'runSettingsSocket' and 'runTLSSocket' functions, principally:

- 'runSettingsSocket' (and functions that eventually call it, like 'run') calls the shutdown handler in the warp settings object while 'runTLSSocket' (and functions that eventually call it, like 'runTLS') silently ignore it.

- If the socket passed into 'runSettingsSocket' is closed, the warp thread gracefully terminates. If the socket passed into 'runTLSSocket' is closed, the thread waits forever after the last active client disconnects.

I haven't dug into the warp main loop enough to understand exactly what is going on(maybe this is a good excuse to do so), but I feel as though these two functions should have the same behavior, unless of course I'm missing something here.

**Comment by snoyberg** [comment] 2015-04-08 07:29
I'm not certain (the code you provided seems to have some typos and is using the wrong function names in each snippet), but I think you're reporting a real issue. My guess is that your analysis is in fact correct. Since you're currently reproducing this, would you be able to take a stab at tweaking warp-tls to respect the necessary flags?

**Comment by kazu-yamamoto** [comment] 2015-04-09 03:40
@TravisWhitaker Your observation is correct. Please read `acceptConnection` in `Run.hs`. 

When a listen socket is closed, `acceptLoop` returns and `gracefulShutdown ` is called. So, a listen socket must be closed for graceful shutdown.

**Comment by kazu-yamamoto** [comment] 2015-04-09 03:55
`settingsInstallShutdownHandler` is used to install a handler to shutdown a listen socket, for instance, for SIGHUP. In your case, `safeShutdown` closes a listen socket. So, `settingsInstallShutdownHandler`is not related to your issue.

**Comment by kazu-yamamoto** [comment] 2015-04-09 03:57
I guess that `try getConnMaker` does not return `Left` in TLS even if a listen socket is closed.

**Comment by kazu-yamamoto** [comment] 2015-04-09 04:00
@snoyberg `runTLSSocket` should call `settingsInstallShutdownHandler` anyway.

**Comment by TravisWhitaker** [comment] 2015-04-21 15:19
Sorry for the delay, I've been busy with a few other projects and this issue wasn't a showstopper. I'll pretty up my branch and send a pull request as soon as I get a few free hours.

@kazu-yamamoto is correct, the connection maker set up by `runTLSSocket'` doesn't return `Left` even if its socket is closed.

**Comment by kazu-yamamoto** [comment] 2015-04-24 05:34
We need to ask the tls maintainer that this is a bug or a spec.

**Comment by kazu-yamamoto** [comment] 2015-05-13 05:34
I think I understand the source of this problem. `getter` in WarpTLS.hs uses `acceptSafe` which is imported `Data.Streaming.Network`. This function never ends: https://hackage.haskell.org/package/streaming-commons-0.1.0.0/docs/src/Data-Streaming-Network.html#acceptSafe

@snoyberg We should do two things:
- WarpTLS should use `accept` to share the accept logic with Warp if you don't have strong reason to use `acceptSafe`.
- `acceptSafe` should steal `isFullErrorType (ioeGetErrorType e)` from Warp's `Run.hs` to loop only when "Too many open files" happens.

@TravisWhitaker Could you modify WarpTLS so that it uses `accept` and test it?

**Comment by kazu-yamamoto** [comment] 2015-05-15 00:04
Pinging @snoyberg.

**Comment by snoyberg** [comment] 2015-05-15 04:11
@kazu-yamamoto is https://github.com/fpco/streaming-commons/commit/f3d5cd2b51e4fec2322a23df91fc69ec2e155dc5 what you were getting at?

**Comment by kazu-yamamoto** [comment] 2015-05-15 04:24
Yes!

**Comment by snoyberg** [comment] 2015-05-15 04:39
OK, released. Does this mean @TravisWhitaker should be able to test with the new version of streaming-commons (0.1.12.1)?

**Comment by kazu-yamamoto** [comment] 2015-05-15 06:03
@snoyberg We should use `accept` instead of `acceptSafe` in WarpTLS to avoid the logic overlapping.

**Comment by snoyberg** [comment] 2015-05-15 06:04
Why not have warp use `acceptSafe` instead?

**Comment by kazu-yamamoto** [comment] 2015-05-15 10:19
Simply replacing `accept` with `acceptSafe` in `Run.hs` does not make sense to me. Would you show me the code which you intend?

**Comment by snoyberg** [comment] 2015-05-15 10:23
That *is* what I intended. I think I'm misunderstanding what's going on here. Is it intentional for `accept` from warp and `acceptSafe` from streaming-commons to have different behavior?

**Comment by kazu-yamamoto** [comment] 2015-05-15 10:28
Please give a look at `acceptNewConnection` in Run.hs. This code includes `isFullErrorType (ioeGetErrorType e)` in the different level of `acceptSafe`. To share this code, I think we should replace `acceptSafe` to `accept` in WarpTLS.

**Comment by snoyberg** [comment] 2015-05-17 07:08
OK, I understand what you're saying now. When you said "use `accept` to share logic with warp", I thought you meant using a function from warp, not using the standard accept. I understand now that warp is already applying that logic to the function in warp-tls.

So to confirm: you mean to replace acceptSafe with Network.Socket.accept in warp-tls, and warp will handle the necessary retry logic by wrapping that call to accept with acceptConnection (Run.hs line 161), correct?

**Comment by kazu-yamamoto** [comment] 2015-05-18 02:43
Yes, exactly. Sorry for my poor explanation.

**Comment by snoyberg** [comment] 2015-05-18 04:28
OK, change pushed. Unless there are objections I can release this.

eed0bf9

**Comment by kazu-yamamoto** [comment] 2015-05-18 04:40
@TravisWhitaker Could you check if the patch above solves your problem?

**Comment by kazu-yamamoto** [comment] 2015-06-12 00:26
I would close this. Please reopen if necessary.

**Closed by kazu-yamamoto** 2015-06-12 00:26 UTC
Labels: ready
