### ISSUE TITLE
Warp sends response bodies for HEAD requests

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/wai#468] opened 2015-11-19 10:06 UTC
Simple repro: run the following minimal Warp application:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Network.Wai
import Network.Wai.Handler.Warp
import Network.HTTP.Types

main :: IO ()
main = run 3000 $ \_ respond -> respond $ responseLBS status200 [] "This body should not appear for HEAD"
```

Then make a HEAD request:

    curl -i -X HEAD http://localhost:3000

Expected: the body does not appear

Actual: it does

It seems like this can be resolved easily by modifying `hasBody` (in Response.hs) to check not only the status code, but also the request method. However, the comments in that module quite clearly say that HEAD was intentionally left in. though I'm not sure what the reason is. (I also have a suspicion that I'm the one who made that decision...)

@kazu-yamamoto Can you see any objection to making the modification to `hasBody` that I just described?

**Comment by kazu-yamamoto** [comment] 2015-11-19 14:04
Isn't this bug specific to HTTP/2? Does this occur even in HTTP/1.1?

**Comment by snoyberg** [comment] 2015-11-19 14:34
I'm uncertain of http 2, but it definitely applies to 1.1, which is where I
was testing

**Comment by kazu-yamamoto** [comment] 2015-11-20 04:25
OK. The problem is that `isHead` is only used for files. No objection to include `isHead` to `hasBody`. 

We should check if we can remove `isHead` from `sendRsp` for `RspFile`.

**Comment by kazu-yamamoto** [comment] 2015-11-24 03:52
The patch above lifts up the `isHead` guard. With this change, Content-Length: is now not added to a response to `HEAD`. But it is valid in RFC7230.

I think this patch makes the logic simpler. @snoyberg What do you think?

**Comment by snoyberg** [comment] 2015-11-24 03:55
I don't feel strongly about it, I'm fine either way.

**Comment by kazu-yamamoto** [comment] 2015-11-24 04:18
Merged. Please check.

**Closed** 2015-11-24 04:18 UTC
Labels: in progress

**Comment by snoyberg** [comment] 2015-11-24 04:25
Confirmed working on master :)

**Comment by kazu-yamamoto** [comment] 2015-12-02 01:37
@snoyberg After reading RFCs again, I should admit that I was wrong about the issue of HEAD's content-length. Your original code is correct since HEAD should behave as GET excepting no body. The logic, for instance, for range should be shared by GET and HEAD.

I have reverted 0297412e7f745eaf5c480fbb914a041fb37c80d4 and 22450c7b00b66d3093a882b2dc2c03a5b9028a3e in my local branch.
