### ISSUE TITLE
toBufIOWith: BufferFull: minSize

### ISSUE THREAD

**Issue by basvandijk** [yesodweb/wai#894] opened 2022-07-26 09:29 UTC
* Your OS name and version: **NixOS-22.05, Linux kernel 5.15.53**
* The versions of tools you're using: **GHC-9.2.3**
* The versions of dependencies you're using: [cabal.project.freeze](https://gist.github.com/basvandijk/8b6d4e000d66655fc044888fcce5634a#file-cabal-project-freeze)

I have a warp-3.3.20 web-server that is serving a prometheus `/metrics` endpoint using the [prometheus-2.2.3](https://hackage.haskell.org/package/prometheus-2.2.3) package. Yesterday it started to occasionally throw the error:

```
Jul 25 19:20:33 XXX XXX[3866464]:
  Request {
    requestMethod = "GET",
    httpVersion = HTTP/1.1,
    rawPathInfo = "/metrics",
    rawQueryString = "",
    requestHeaders = [
      ("Connection","close"),
      ("Host","XXX"),
      ("X-Real-IP","XXX"),
      ("X-Forwarded-For","XXX"),
      ("X-Forwarded-Proto","https"),
      ("X-Forwarded-Host","XXX"),
      ("X-Forwarded-Server","XXX"),
      ("User-Agent","Prometheus/2.23.0"),
      ("Accept","application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"),
      ("Accept-Encoding","gzip"),
      ("X-Prometheus-Scrape-Timeout-Seconds","10.000000")
    ],
    isSecure = False,
    remoteHost = 127.0.0.1:41744,
    pathInfo = ["metrics"],
    queryString = [],
    requestBody = <IO ByteString>,
    vault = <Vault>,
    requestBodyLength = KnownLength 0,
    requestHeaderHost = Just "XXX",
    requestHeaderRange = Nothing
  }
    threw exception: toBufIOWith: BufferFull: minSize
    CallStack (from HasCallStack):
      error, called at ./Network/Wai/Handler/Warp/IO.hs:23:36 in warp-3.3.20-76HAz05JSpF9OEUtOoqO7e:Network.Wai.Handler.Warp.IO
```

(As you might have guessed from the headers, there's a nginx reverse proxy server in front of warp handling TLS termination).

That error is thrown at [`warp/Network/Wai/Handler/Warp/IO.hs#L23`](https://github.com/yesodweb/wai/blob/warp-3.3.20/warp/Network/Wai/Handler/Warp/IO.hs#L23).

The endpoint is implemented by calling [`prometheusApp`](https://hackage.haskell.org/package/prometheus-2.2.3/docs/System-Metrics-Prometheus-Http-Scrape.html#v:prometheusApp) which internally uses [`responseBuilder`](https://hackage.haskell.org/package/wai-3.2.3/docs/Network-Wai.html#v:responseBuilder) to construct a response from a Builder.

I counted 164 failures out of 5017 successes so far. The failures usually happen in bursts sometimes lasting over 10 minutes.

Note that this web-server is also serving lots of other endpoints. Serving `/metrics` only makes up about 3% of overall traffic but it's the only endpoint that is failing.

The most significant change is that I upgraded GHC from 9.0.2 to 9.2.3 yesterday at 11:17 UTC. The first error appeared 8 hours later at 19:20 that day.

Any idea why this is happening?

**Comment by basvandijk** [comment] 2022-07-26 10:05
I noticed something interesting. The following is a screenshot of a grafana dashboard showing some of the metrics served from the /metrics endpoint. The gaps in the data (clearly marked with the red vertical lines) correspond to the BufferFull errors.  

What's interesting is that the error only seems to happens when the metric goes from >0 to 0 or from 0 to >0.

![Screenshot 2022-07-26 at 11 59 40](https://user-images.githubusercontent.com/576355/180979915-6b07df09-67ba-4f6b-b0d5-7010fb2e843e.png)

**Comment by basvandijk** [comment] 2022-07-26 11:04
These are the differences in dependencies before and after the GHC 9.0.2 -> 9.2.3 upgrade:
```diff
$ diff cabal.project.freeze-GHC-9.0.2 cabal.project.freeze-GHC-9.2.3
31,33c31,33
<              any.base ==4.15.1.0,
<              any.base-compat ==0.11.2,
<              any.base-compat-batteries ==0.11.2,
---
>              any.base ==4.16.2.0,
>              any.base-compat ==0.12.1,
>              any.base-compat-batteries ==0.12.1,
39c39
<              any.binary ==0.8.8.0,
---
>              any.binary ==0.8.9.0,
48,49c48,49
<              any.bytesmith ==0.3.8.0,
<              any.bytestring ==0.10.12.1,
---
>              any.bytesmith ==0.3.9.0,
>              any.bytestring ==0.11.3.1,
61c61
<              any.containers ==0.6.4.1,
---
>              any.containers ==0.6.5.1,
73c73
<              any.deepseq ==1.4.5.0,
---
>              any.deepseq ==1.4.6.1,
85c85
<              any.filepath ==1.4.2.1,
---
>              any.filepath ==1.4.2.2,
88,91c88,91
<              any.ghc-bignum ==1.1,
<              any.ghc-boot-th ==9.0.2,
<              any.ghc-prim ==0.7.0,
<              any.hashable ==1.3.5.0,
---
>              any.ghc-bignum ==1.2,
>              any.ghc-boot-th ==9.2.3,
>              any.ghc-prim ==0.8.0,
>              any.hashable ==1.4.0.2,
121c121
<              any.lens ==5.0.1,
---
>              any.lens ==5.1,
149c149
<              any.opaleye ==0.9.2.0,
---
>              any.opaleye ==0.9.3.0,
155c155
<              any.parsec ==3.1.14.0,
---
>              any.parsec ==3.1.15.0,
209c209
<              any.stm ==2.5.0.0,
---
>              any.stm ==2.5.0.2,
218c218
<              any.template-haskell ==2.17.0.0,
---
>              any.template-haskell ==2.18.0.0,
230c230
<              any.time ==1.9.3,
---
>              any.time ==1.11.1.1,
269a270
>              any.word-compat ==0.0.3,
```
My suspicion is that the bug is caused by the  bytestring 0.10.12.1 -> 0.11.3.1 upgrade ([changelog](https://hackage.haskell.org/package/bytestring-0.11.3.1/changelog)).

**Comment by basvandijk** [comment] 2022-07-26 12:04
Some musings on this:

1. The amount of metrics produced by my /metrics endpoint is about 52 KiB:
```
curl https://XXX/metrics --silent | wc -c
53804
```
2. I see [the buffer size used by warp is 16 KiB](https://sourcegraph.com/github.com/yesodweb/wai@fc0527eee2f4cce1a2405bede9d220d747dc3e61/-/blob/warp/Network/Wai/Handler/Warp/Buffer.hs?L33:1).
3. Since we hit the [`More`](https://hackage.haskell.org/package/bytestring-0.11.3.1/docs/Data-ByteString-Builder-Extra.html#v:More) case in [`toBufIOWith`](https://sourcegraph.com/github.com/yesodweb/wai@fc0527eee2f4cce1a2405bede9d220d747dc3e61/-/blob/warp/Network/Wai/Handler/Warp/IO.hs?L23) and because our metrics are 52 KiB I would expect that `minSize` is probably bigger than the 16 KiB buffer thus triggering the BufferFull error. 

Why does warp error in this case? Can't it just create a bigger buffer at that point?

**Comment by basvandijk** [comment] 2022-07-26 13:52
Currently playing with having a dynamically sized write buffer in: https://github.com/yesodweb/wai/compare/master...basvandijk:wai:dynamic-write-buffer ...

**Comment by basvandijk** [comment] 2022-07-27 07:25
I can confirm that the above patch fixes the BufferFull errors:
![Screenshot 2022-07-27 at 09 17 46](https://user-images.githubusercontent.com/576355/181186971-c62bf302-9da7-4ea7-a0f6-e690337ea023.png)
I'll turn it into a PR.

**Comment by alexbiehl** [comment] 2022-08-09 09:39
@basvandijk I think the issue is caused by a bug in the bytestring library. I've put up a fix for it over at https://github.com/haskell/bytestring/pull/538. Maybe you can give it a shot?

**Comment by Vlix** [comment] 2022-11-02 23:46
It would be nice if @basvandijk could verify this problem has been fixed, but I think I'll close this issue because there's two fixes that seem likely to have resolved this.

**Closed by Vlix** 2022-11-02 23:46 UTC

**Comment by alexbiehl** [comment] 2022-11-03 05:32
It turned out it was a bug in bytestring — I don’t think the new toByfIOWith has anything to do iff bytestring works correctly.
