### ISSUE TITLE
tls ghc 7.6.x linux

### ISSUE THREAD

**Issue by gertcuykens** [yesodweb/wai#138] opened 2013-02-03 02:04 UTC
static errors
`send: resource vanished (Broken pipe)` when using firefox
`Error_EOF` when using chrome

wss errors
`Error_Packet "partial packet: expecting 16416 bytes, got: 4054"`

```html5
<!DOCTYPE html>
<html>
    <head>
        <title>Example</title>
    </head>
    <script>
        dropBox=function(s,d){
         var click=function(e){input.click()}
         var change=function(e){for (var i=0;i<this.files.length;i++){s.send(this.files[i])}}
         var input=document.createElement('input')
         input.type='file'
         input.addEventListener('change',change,false)
         d.addEventListener('click',click,false)
        }
        var wss = new WebSocket('wss://localhost:9160')
        wss.binaryType = 'blob'
        wss.onopen = function(){dropBox(wss,document.getElementById('wss'))}
    </script>
    <body>
        <h1>WSS</h1>
        <img id="wss" src="wss.png"/>
    </body>
</html>
```

```haskell
module Main where
import Control.Monad (forever)
import Control.Monad.IO.Class (liftIO)
import qualified Data.ByteString.Char8 as BS
import qualified Data.ByteString.Lazy.Char8 as BL
import Data.String (fromString)
import Network.Wai.Application.Static (staticApp, defaultWebAppSettings, defaultFileServerSettings)
import Network.Wai.Handler.Warp (runSettings, defaultSettings, settingsIntercept, settingsHost, settingsPort)
import Network.Wai.Handler.WarpTLS (TLSSettings(..), runTLS)
import Network.Wai.Handler.WebSockets (intercept)
import qualified Network.WebSockets as WS

defaultTLS :: TLSSettings
defaultTLS = TLSSettings "ssl/cert.pem" "ssl/key.pem"

loop :: WS.Request -> WS.WebSockets WS.Hybi10 ()
loop r' = WS.acceptRequest r' >> forever (WS.receiveData >>= liftIO . BL.writeFile "wss.png")

main :: IO ()
main = do
    runTLS defaultTLS defaultSettings
        { settingsPort = 9160
        , settingsIntercept = intercept loop
        } $ staticApp (defaultFileServerSettings $ fromString ".")
```

```cabal
name: test-tls
version: 0.1.0.0
build-type: Simple
cabal-version: >=1.8
data-files: *.htm, *.png, *.pem

executable test-tls
    main-is: Main.hs
    ghc-options: -Wall
    build-depends: base >=4.6
                 , bytestring >=0.10
                 , transformers >=0.3
                 , websockets >=0.7
                 , tls >=1.1
                 , warp >=1.3
                 , warp-tls >=1.3
                 , wai-websockets >=1.3
                 , wai-app-static >=0.2
                 , wai-extra >=1.3
```

**Comment by snoyberg** [comment] 2015-07-19 21:09
Closing as cannot reproduce, especially since GHC has has many releases since these reports.

**Closed by snoyberg** 2015-07-19 21:09 UTC
