### ISSUE TITLE
warp 3.1.4 fails to build on Windows in Recv.hs

### ISSUE THREAD

**Issue by joeyh** [yesodweb/wai#441] opened 2015-10-04 19:04 UTC
Network\Wai\Handler\Warp\Recv.hs:129:16:
    Couldn't match expected type `CInt' with actual type `IO a0'
    Relevant bindings include
      bytes :: IO a0 (bound at Network\Wai\Handler\Warp\Recv.hs:117:5)
    In the first argument of `return', namely `bytes'
    In the expression: return bytes

This is using ghc 7.10.2. warp 3.1.3.1 builds ok.

**Comment by awpr** [comment] 2015-10-04 21:18
Duplicate of #438.   May as well leave this one open for visibility until the fix is released, though.

**Comment by nlinker** [comment] 2015-10-05 14:25
`cabal install wai-3.0.3.0 --reinstall` and then `cabal install warp-3.1.3` builds ok as well.

**Comment by kazu-yamamoto** [comment] 2015-10-13 06:36
A new version has been released.

**Closed by kazu-yamamoto** 2015-10-13 06:36 UTC
