### ISSUE TITLE
Access log sequence not valid

### ISSUE THREAD

**Issue by netroby** [yesodweb/wai#336] opened 2015-02-14 22:29 UTC
I noticed the access log print does not valid.
```
GET /static/css/bootstrap.css
  Params: [("etag","4pWKTr6R")]
  Accept: text/css,*/*;q=0.1
GET /static/tmp/autogen-vozS04Wr.css
  Accept: text/css,*/*;q=0.1
  Status: 200 OK 0.000098s
  Status: 200 OK 0.000031s
```
I guess the right sequence should be
```
GET /static/css/bootstrap.css
  Params: [("etag","4pWKTr6R")]
  Accept: text/css,*/*;q=0.1
  Status: 200 OK 0.000098s
GET /static/tmp/autogen-vozS04Wr.css
  Accept: text/css,*/*;q=0.1
  Status: 200 OK 0.000031s
```

**Comment by gregwebs** [comment] 2015-02-14 22:32
This is from yesodweb/wai#283

We should change to logging only when the request is complete.

**Comment by nikuda** [comment] 2015-02-16 02:41
Ah strange, I'll have a look at this too.

**Comment by snoyberg** [comment] 2015-02-25 05:20
Bump

**Comment by netroby** [comment] 2015-02-25 05:21
@snoyberg  is it ok now?

**Comment by snoyberg** [comment] 2015-02-25 05:24
I don't think so, I was bumping to @nikuda actually.

**Comment by nikuda** [comment] 2015-02-25 06:16
Sorry guys, will look at this first thing tomorrow.

@netroby can you provide a little more info on when does this happen? Is it only with those 2 files? Does it happen all the time or is it sporadic? How are you including those 2 files? Thanks.

**Comment by netroby** [comment] 2015-02-25 06:19
https://github.com/yesodweb/yesod-scaffold

I am test via the hello world of yesod framework. i noticed the log not the right sequence. it was very easy to reproduce .

**Comment by nikuda** [comment] 2015-02-25 06:21
Got it, thanks.

**Comment by nikuda** [comment] 2015-02-27 03:38
How do I get the scaffold to work? The build is complaining about merging git branches?

**Comment by netroby** [comment] 2015-02-27 03:41
http://www.yesodweb.com/page/quickstart

Do as the quickstart said:

```
wget http://www.stackage.org/lts/cabal.config
cabal update                       # download package list
cabal install alex happy yesod-bin # install build tools
yesod init --bare                  # answer questions as prompted
cabal sandbox init                 # set up a sandbox
cabal install --run-tests          # install libraries
yesod devel                        # launch devel server
```
Open browser try to visit the demo page http://127.0.0.1:3000


and see the log out print on the terminal screen

**Comment by nikuda** [comment] 2015-02-27 07:01
After getting `global constraint requires installed instance` errors I wiped GHC off OSX hoping it would be the quickest way to get things back in order, and now I'm getting this:

```
cabal: Could not resolve dependencies:
trying: alex-3.1.4 (user goal)
trying: QuickCheck-2.7.6 (dependency of alex-3.1.4)
trying: transformers-0.4.2.0/installed-42d... (dependency of QuickCheck-2.7.6)
trying: yesod-bin-1.4.3.10 (user goal)
next goal: ghc (dependency of yesod-bin-1.4.3.10)
rejecting: ghc-7.8.3/installed-4d8... (conflict:
transformers==0.4.2.0/installed-42d..., ghc =>
transformers==0.3.0.0/installed-16a...)
Backjump limit reached (change with --max-backjumps).
```

In my experience the dependency conflicts happen a little too frequently with with Yesod. Maybe it's just the sheer amount of libraries it uses.

**Comment by snoyberg** [comment] 2015-02-27 07:10
Did you follow the installation guide? This is one of the standard "cabal
sucks" moments, and is solved completely by the usage of a Stackage config
file.

**Comment by snoyberg** [comment] 2015-02-27 07:32
A tl;dr of how to get those constraints in place easily would be `wget
http://www.stackage.org/nightly/cabal.config`. If you're going to be
playing around with wai-extra, you may need to delete that line from the
cabal.config file.

**Comment by nikuda** [comment] 2015-02-27 07:52
Thanks. The Stackage config file did fix that problem. Although now I'm getting this on attempting to install `yesod-bin` (GHC7.8.3 on OSX).

```
cabal: The following packages are likely to be broken by the reinstalls:
HTTP-4000.2.19
```

**Comment by snoyberg** [comment] 2015-02-27 07:53
That's because you have preexisting packages from your old install. Either
follow the instructions and force reinstalls or use sandboxes.

**Comment by nikuda** [comment] 2015-03-02 01:42
Thanks @snoyberg. Force reinstalled.

@netroby when you say hello world of yesod, do you mean the default welcome scaffold page that gets generated? Or did you do another tutorial that makes it happen? With the default welcome page I get expected output:

```
GET /static/css/bootstrap.css
  Params: [("etag","QRP3qj9r")]
  Accept: text/css,*/*;q=0.1
  Status: 304 Not Modified 0.000113s
GET /static/tmp/autogen-vozS04Wr.css
  Accept: text/css,*/*;q=0.1
  Status: 304 Not Modified 0.000068s
```

**Comment by gregwebs** [comment] 2015-03-02 01:46
@nikuda the issue is not deterministic

**Comment by netroby** [comment] 2015-03-02 04:41
@nikuda yes, i means the default welcome scaffold.

**Comment by nikuda** [comment] 2015-03-03 01:06
This patch fixes the issue: nikuda/wai@46adf4006e4de0099ecffc7338a2f48649c76c95

@gregwebs Do you see any problems with the patch? I vaguely remember an uncertainty around the placement of that 'log the request immediately' code in another discussion.

**Comment by snoyberg** [comment] 2015-03-03 06:59
I've added a comment on the patch.

**Comment by nikuda** [comment] 2015-03-04 03:45
Good catch @snoyberg.

Updated patch: nikuda/wai@0f651eaefc42f4d59c29127c8eb669d15ac974b7

**Comment by gregwebs** [comment] 2015-03-04 03:55
The change is good, but the code was structured a different way to satisfy one use case: a very long request. This log now has a problem reminiscent of the slowloris logging problem. If you have an infinite loop in your code you may never see a log of the request that produced the infinite loop (the loop may crash your server).

The reason we have this problem in the first place is because @nikuda was adapting my code that was specifically meant to address the unlogged request issue.

On the whole, this change is for the better. I don't know how to solve the problem mentioned without introducing awkwardness to the log in the normal operation case.

**Comment by snoyberg** [comment] 2015-03-04 07:07
Fix merged, thanks!

**Closed by snoyberg** 2015-03-04 07:07 UTC
