### ISSUE TITLE
[warp] Support h2c for HTTP/2

### ISSUE THREAD

**Issue by iand675** [yesodweb/wai#615] opened 2017-02-23 00:47 UTC
I know that there are good reasons for encouraging browsers to use HTTP/2 exclusively over TLS, but it would be nice for warp to support h2c (non-TLS encrypted HTTP/2 traffic).

The use case here is that it's very common for something like HAProxy or ELB to do TLS termination and send unencrypted traffic within the private network. It would be really nice to not have to deal with setting up end-to-end TLS in order to be able to actually use warp's HTTP/2 support in real-world deployments.

**Comment by kazu-yamamoto** [comment] 2017-02-23 21:26
Warp supports direct HTTP/2!
Try connect to Warp with `h2load`, for example.
The issue is HTTP client side!

**Comment by kazu-yamamoto** [comment] 2017-04-06 02:44
@iand675 Can we close this issue?

**Comment by kazu-yamamoto** [comment] 2017-05-30 07:14
Let's close.

**Closed by kazu-yamamoto** 2017-05-30 07:14 UTC
