### ISSUE TITLE
wai-extra Gzip doesn't appear to compress output

### ISSUE THREAD

**Issue by axman6** [yesodweb/wai#536] opened 2016-04-21 04:45 UTC
I'm building a simple web app which produces highly compressible data as CSVs using the servant-cassava package (uncompressed size is over 6MB so should definitely be compressed). I'm finding that when using the gzip middleware, our content is marked as being encoded as gzip, but is not reduced in size at all. The content type of the result is `text/csv;charset=utf-8`, which appears to be covered by the `text/` check.

Also the documentation in the module is very unhelpful, it took reading the source code to find out that it was actually possible to set the values of `GzipSettings` - just export `GzipSettings{..}` instead of exporting the accessors separately.

Sadly this app isn't likely to be open source for quite a while, but I may be able to make a minimal example if necessary.

**Comment by axman6** [comment] 2016-04-21 04:56
Looking at the code, the `GzipCompress` constructor of `GzipFiles` isn't actually used anywhere, what is it even supposed to do?

**Comment by snoyberg** [comment] 2016-04-22 06:18
Documentation improvements would definitely be accepted as a PR.

As for behavior of `GzipCompress`, my guess is that through a refactoring at some point, that functionality was removed. I don't see any reason to avoid adding it back, though.

**Comment by psibi** [comment] 2016-04-23 07:39
One way of solving this would be by changing the default instance of `GzipSettings`. Another way would be to override the function `gzip`  in a way such that no matter what value is passed in `gzipFiles` for the record `GzipSettings` , we set it to `GzipCompress`.

Another way would be to change the signature to `gzip :: Bool -> Middleware`, like it was done previously. But that will break backward compatibility. I like the second solution. Any thoughts ?

**Comment by axman6** [comment] 2016-04-25 23:52
None of this seems to deal with the fact the data isn't actually being compressed. Apparently we're not alone though, I'm seeing the same behaviour from varnish or nginx (we're not sure which just yet) the first time we request data from a specific URL, but not from subsequent requests.

**Comment by snoyberg** [comment] 2016-04-27 11:50
> Looking at the code, the GzipCompress constructor of GzipFiles isn't actually used anywhere, what is it even supposed to do?

I reviewed the code again, and in fact `GzipCompress` _is_ used via the fall-through on line 92. But the code is very difficult to parse. I'm going to test a theory...

**Comment by snoyberg** [comment] 2016-04-27 12:02
I just confirmed that compressing files works as expected:

```haskell
import Network.Wai
import Network.Wai.Middleware.Gzip
import Network.Wai.Handler.Warp
import Network.HTTP.Types

main :: IO ()
main = run 3000 $ gzip def { gzipFiles = GzipCompress }
                $ \_ send -> send $ responseFile status200 [("content-type", "text/markdown")] "ChangeLog.md" Nothing
```

Caveats:

* Make sure you're passing `accept-encoding`
* The file has to be at least 860 bytes in size
* You must set `GzipCompress` as I did in this snippet

If this isn't working for you still, can you provide a code snippet that demonstrates the problem?

**Comment by snoyberg** [comment] 2016-07-05 12:54
Bump, any feedback on my comment above?

**Comment by axman6** [comment] 2016-07-06 03:52
Hey, Sorry Michael, this dropped off my radar, I will try and find time this week, but it's a pretty bad time for us.

I wonder if the fact that we're returning a lazy bytestreing, which appears to have a chunked encoding, means that gzip compression does happen, as it seems to send each row of our csv as a chunk (which is far from ideal). I will look into this as well if I can find time.

**Comment by tolysz** [comment] 2016-09-07 11:39
Sorry for the late jump it, Is the generated output saved as a file then served to the client? OR it is `conduit` to the client directly from the producer?
The 1st would benefit from different `gzipFiles` (my favourite `GzipPreCompressed GzipIgnore` :P ) settings the later will not.

**Comment by ip1981** [comment] 2016-11-15 09:13
This works for me https://github.com/zalora/mywatch/commit/bb607424b947f1dad571fe05c2044646073de201

I can see in firefox console that dynamic and static files are compressed.

**Comment by snoyberg** [comment] 2016-11-16 11:26
It sounds like this is all working as expected now, closing. If there is a counter example, let's reopen or start a new issue.

**Closed by snoyberg** 2016-11-16 11:26 UTC
